### ISSUE TITLE
Finalizerの名前

### ISSUE THREAD

**Issue by masa213f** [zoetrope/kubebuilder-training#36]
Fainalizerの節で例として書いてあるfainalizer(以下)は設定できないようです。

```
metadata:
  finalizers:
  - markdownview.finalizers.view.zoetrope.github.io
```

次のようなエラーではじかれました。
```
# configmaps "test" was not valid:
# * metadata.finalizers[0]: Invalid value: "markdownview.finalizers.view.zoetrope.github.io": name is neither a standard finalizer name nor is it fully qualified
```

`/`区切りじゃないとダメみたいですね。

https://github.com/kubernetes/kubernetes/blob/v1.24.3/pkg/apis/core/validation/validation.go#L5966-L5976
https://github.com/kubernetes/kubernetes/blob/v1.24.3/pkg/apis/core/helper/helpers.go#L293-L302

**Comment by zoetrope** [comment]
@masa213f 
あざっす。
ちゃんと動くコードがないとダメですね…。
